/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import java.awt.Dimension;
import javax.swing.*;
import javax.swing.JTextField;
import java.sql.*;
import java.util.Vector;
import conexion.Conexion;



/**
 *
 * @author LENOVO
 */
public class JInternalFrameTablaClientes extends javax.swing.JInternalFrame {

    
    public JInternalFrameTablaClientes() {
        initComponents();
        this.setSize(new Dimension(894, 553));
        //this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setTitle("Clientes");
        cargarDistritosAutoCompletar(DistritoCLiente);
    }
    private void cargarDistritosAutoCompletar(JComboBox comboBox) {
    try {
        Connection con = Conexion.establecerConexion();
        String sql = "SELECT Nombre FROM Distrito ORDER BY Nombre";
        PreparedStatement ps = con.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();

        // Lista original de distritos
        Vector<String> distritos = new Vector<>();
        while (rs.next()) {
            distritos.add(rs.getString("Nombre"));
        }

        comboBox.setEditable(true);
        comboBox.setModel(new DefaultComboBoxModel(distritos));
        JTextField editor = (JTextField) comboBox.getEditor().getEditorComponent();

        editor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                String texto = editor.getText();

                if (texto.length() == 0) {
                    comboBox.hidePopup();
                    return;
                }

                // Solo busca coincidencias que EMPIECEN por el texto
                Vector<String> coincidencias = new Vector<>();
                for (String item : distritos) {
                    if (item.toLowerCase().startsWith(texto.toLowerCase())) {
                        coincidencias.add(item);
                    }
                }

                if (!coincidencias.isEmpty()) {
                    comboBox.setModel(new DefaultComboBoxModel(coincidencias));
                    comboBox.setSelectedItem(texto);
                    comboBox.showPopup();
                } else {
                    comboBox.hidePopup();
                }
            }
        });

        con.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al cargar distritos: " + e.getMessage());
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmpleados = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtApellidosNClientes = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNombresCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtContraNCliente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNumDocNCliente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTelefonoNCliente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCorreoNCliente = new javax.swing.JTextField();
        cbxDireccionNCliente = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtNUsuarioCliente = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        NumLicencia = new javax.swing.JTextField();
        DistritoCLiente = new javax.swing.JComboBox<>();
        cbxNacionaNCliente1 = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Administrar Clientes");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTableEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableEmpleados);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 710, 250));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("ACTUALIZAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jButton2.setText("ELIMINAR");
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 100, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, 140, 90));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Apellidos:");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        txtApellidosNClientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidosNClientesKeyTyped(evt);
            }
        });
        jPanel6.add(txtApellidosNClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 180, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Nombres:");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txtNombresCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresClienteActionPerformed(evt);
            }
        });
        txtNombresCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombresClienteKeyTyped(evt);
            }
        });
        jPanel6.add(txtNombresCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 180, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Nacionalidad:");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Distrito:");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Contraseña:");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        txtContraNCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContraNClienteKeyTyped(evt);
            }
        });
        jPanel6.add(txtContraNCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 180, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Numero de Doc:");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, -1));

        txtNumDocNCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumDocNClienteKeyTyped(evt);
            }
        });
        jPanel6.add(txtNumDocNCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 180, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Teléfono:");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        txtTelefonoNCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoNClienteKeyTyped(evt);
            }
        });
        jPanel6.add(txtTelefonoNCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 180, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Correo:");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, -1, -1));

        txtCorreoNCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCorreoNClienteKeyTyped(evt);
            }
        });
        jPanel6.add(txtCorreoNCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 180, -1));

        cbxDireccionNCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cbxDireccionNClienteKeyTyped(evt);
            }
        });
        jPanel6.add(cbxDireccionNCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 180, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Dirección:");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        txtNUsuarioCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNUsuarioClienteKeyTyped(evt);
            }
        });
        jPanel6.add(txtNUsuarioCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 180, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Usuario:");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Numero de licencia:");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, -1, -1));

        NumLicencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NumLicenciaKeyTyped(evt);
            }
        });
        jPanel6.add(NumLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 180, -1));

        DistritoCLiente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Especificado", "Peruana", "Extranjera" }));
        jPanel6.add(DistritoCLiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 180, -1));

        cbxNacionaNCliente1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Especificado", "Peruana", "Extranjera" }));
        jPanel6.add(cbxNacionaNCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 180, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 860, 180));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtNombresClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresClienteKeyTyped
        String text= txtNombresCliente.getText();//texto actual
        int lim=30;
        if(text.length()>= lim) evt.consume();
        
        char c= evt.getKeyChar();//c= caracter actual
        // Permite solo letras
        if (!Character.isLetter(c) && c != ' ') {
        evt.consume();
        return;
        }
        // Permite máximo un espacio
        if (c == ' ' && text.contains(" ")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombresClienteKeyTyped

    private void txtNombresClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresClienteActionPerformed

    private void txtApellidosNClientesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosNClientesKeyTyped
        String text= txtApellidosNClientes.getText();//texto actual
        int lim=30;
        if(text.length()>= lim) evt.consume();
        
        char c= evt.getKeyChar();//c= caracter actual
        // Permite solo letras
        if (!Character.isLetter(c) && c != ' ') {
        evt.consume();
        return;
        }
        // Permite máximo un espacio
        if (c == ' ' && text.contains(" ")) {
            evt.consume();
        }
        
    }//GEN-LAST:event_txtApellidosNClientesKeyTyped

    private void txtNUsuarioClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNUsuarioClienteKeyTyped
              String text = txtNUsuarioCliente.getText(); // texto actual
int lim = 30;
if (text.length() >= lim) evt.consume();

char c = evt.getKeyChar(); // carácter actual

// Permite solo letras y máximo un espacio
if (!Character.isLetter(c) && c != ' ') {
    evt.consume();
    return;
}

// Solo se permite un espacio en todo el texto
if (c == ' ' && text.contains(" ")) {
    evt.consume();
}

    }//GEN-LAST:event_txtNUsuarioClienteKeyTyped

    private void txtContraNClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraNClienteKeyTyped
                String text = txtContraNCliente.getText();
int lim = 24;
if (text.length() >= lim) {
    evt.consume();
}

char c = evt.getKeyChar();
String allowedSymbols = "@_-!.#";

// Permitir letras, números y algunos símbolos comunes
if (!Character.isLetterOrDigit(c) && allowedSymbols.indexOf(c) == -1) {
    evt.consume();
}

    }//GEN-LAST:event_txtContraNClienteKeyTyped

    private void txtTelefonoNClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoNClienteKeyTyped
                String text= txtTelefonoNCliente.getText();
        int lim=9;
        if(text.length() >=9) evt.consume();
        char c=evt.getKeyChar(); //caracter actual
        if(!(Character.isDigit(c))){evt.consume();}
    }//GEN-LAST:event_txtTelefonoNClienteKeyTyped

    private void txtCorreoNClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoNClienteKeyTyped
        String text = txtCorreoNCliente.getText(); // texto actual
int lim = 40;
if (text.length() >= lim) evt.consume();

char c = evt.getKeyChar(); // carácter actual

// Permitidos: letras, números y símbolos básicos de correo
String permitidos = "@._-";
if (!Character.isLetterOrDigit(c) && permitidos.indexOf(c) == -1) {
    evt.consume();
}
    }//GEN-LAST:event_txtCorreoNClienteKeyTyped

    private void cbxDireccionNClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbxDireccionNClienteKeyTyped
        String text = cbxDireccionNCliente.getText(); // texto actual
int lim = 50;
char c = evt.getKeyChar(); // carácter actual

// Limitar longitud
if (text.length() >= lim) {
    evt.consume();
    return;
}

// Permitir letras, números y un solo espacio entre palabras
if (!Character.isLetterOrDigit(c) && c != ' ') {
    evt.consume();
    return;
}

// Evitar espacio inicial
if (text.isEmpty() && c == ' ') {
    evt.consume();
    return;
}

// Evitar más de un espacio seguido
if (c == ' ' && text.endsWith(" ")) {
    evt.consume();
}
    }//GEN-LAST:event_cbxDireccionNClienteKeyTyped

    private void txtNumDocNClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumDocNClienteKeyTyped
        String text = txtNumDocNCliente.getText();
int lim = 12; // Ajusta el límite según el tipo de documento

char c = evt.getKeyChar();
if (text.length() >= lim || !Character.isDigit(c)) {
    evt.consume();
}
    }//GEN-LAST:event_txtNumDocNClienteKeyTyped

    private void NumLicenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NumLicenciaKeyTyped
        String text = NumLicencia.getText(); // texto actual
int lim = 15;
if (text.length() >= lim) evt.consume();

char c = evt.getKeyChar(); // carácter actual
// Permitir solo números y letras, sin espacios ni símbolos
if (!Character.isLetterOrDigit(c)) {
    evt.consume();
}

    }//GEN-LAST:event_NumLicenciaKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> DistritoCLiente;
    private javax.swing.JTextField NumLicencia;
    private javax.swing.JTextField cbxDireccionNCliente;
    private javax.swing.JComboBox<String> cbxNacionaNCliente1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEmpleados;
    private javax.swing.JTextField txtApellidosNClientes;
    private javax.swing.JTextField txtContraNCliente;
    private javax.swing.JTextField txtCorreoNCliente;
    private javax.swing.JTextField txtNUsuarioCliente;
    private javax.swing.JTextField txtNombresCliente;
    private javax.swing.JTextField txtNumDocNCliente;
    private javax.swing.JTextField txtTelefonoNCliente;
    // End of variables declaration//GEN-END:variables
}
