package vista;

import java.awt.Dimension;

/**
 *
 * @author LENOVO
 */
public class JInternalFrameRegEntrada extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalFrameRegEntrada
     */
    public JInternalFrameRegEntrada() {
        initComponents();
        this.setSize(new Dimension(400,200));
        this.setTitle("Registro Entrada");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
