/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import java.awt.Dimension;

public class JInternalFrameTablaEmpleados extends javax.swing.JInternalFrame {

    
    public JInternalFrameTablaEmpleados() {
        initComponents();
        this.setSize(new Dimension(894, 553));
        this.setTitle("Empleados");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmpleados = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtApellidosNEmpleados = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNombresEmpleado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtContraNEmpleado = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNumDocNEmpleado = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTelefonoNEmpleado = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCorreoNCEmpleado = new javax.swing.JTextField();
        cbxDireccionNEmpleado = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtNUsuarioEmpleado = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cbxNacionaNEmpleado = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Administrar Empleados");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTableEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableEmpleados);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 710, 250));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("ACTUALIZAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jButton2.setText("ELIMINAR");
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 100, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, 140, 90));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Apellidos:");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        txtApellidosNEmpleados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidosNEmpleadosKeyTyped(evt);
            }
        });
        jPanel6.add(txtApellidosNEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 180, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Nombres:");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txtNombresEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombresEmpleadoKeyTyped(evt);
            }
        });
        jPanel6.add(txtNombresEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 180, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Nacionalidad:");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Distrito:");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));
        jPanel6.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 180, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Contraseña:");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        txtContraNEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContraNEmpleadoKeyTyped(evt);
            }
        });
        jPanel6.add(txtContraNEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 180, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Numero de Doc:");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, -1));

        txtNumDocNEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumDocNEmpleadoKeyTyped(evt);
            }
        });
        jPanel6.add(txtNumDocNEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 180, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Teléfono:");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, -1, -1));

        txtTelefonoNEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoNEmpleadoKeyTyped(evt);
            }
        });
        jPanel6.add(txtTelefonoNEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 180, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Correo:");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, -1, -1));

        txtCorreoNCEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCorreoNCEmpleadoKeyTyped(evt);
            }
        });
        jPanel6.add(txtCorreoNCEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 180, -1));

        cbxDireccionNEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cbxDireccionNEmpleadoKeyTyped(evt);
            }
        });
        jPanel6.add(cbxDireccionNEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 180, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Dirección:");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        txtNUsuarioEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNUsuarioEmpleadoKeyTyped(evt);
            }
        });
        jPanel6.add(txtNUsuarioEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 180, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Usuario:");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, -1, -1));

        cbxNacionaNEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Especificado", "Peruana", "Extranjera" }));
        jPanel6.add(cbxNacionaNEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 180, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 860, 180));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtNombresEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresEmpleadoKeyTyped
        String text= txtNombresEmpleado.getText();//texto actual
        int lim=30;
        if(text.length()>= lim) evt.consume();
        
        char c= evt.getKeyChar();//c= caracter actual
        // Permite solo letras
        if (!Character.isLetter(c) && c != ' ') {
        evt.consume();
        return;
        }
        // Permite máximo un espacio
        if (c == ' ' && text.contains(" ")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombresEmpleadoKeyTyped

    private void txtApellidosNEmpleadosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosNEmpleadosKeyTyped
        String text= txtApellidosNEmpleados.getText();//texto actual
        int lim=30;
        if(text.length()>= lim) evt.consume();
        
        char c= evt.getKeyChar();//c= caracter actual
        // Permite solo letras
        if (!Character.isLetter(c) && c != ' ') {
        evt.consume();
        return;
        }
        // Permite máximo un espacio
        if (c == ' ' && text.contains(" ")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtApellidosNEmpleadosKeyTyped

    private void txtNUsuarioEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNUsuarioEmpleadoKeyTyped
              String text = txtNUsuarioEmpleado.getText(); // texto actual
int lim = 30;
if (text.length() >= lim) evt.consume();

char c = evt.getKeyChar(); // carácter actual

// Permite solo letras y máximo un espacio
if (!Character.isLetter(c) && c != ' ') {
    evt.consume();
    return;
}

// Solo se permite un espacio en todo el texto
if (c == ' ' && text.contains(" ")) {
    evt.consume();
}

    }//GEN-LAST:event_txtNUsuarioEmpleadoKeyTyped

    private void txtContraNEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraNEmpleadoKeyTyped
                String text = txtContraNEmpleado.getText();
int lim = 24;
if (text.length() >= lim) {
    evt.consume();
}

char c = evt.getKeyChar();
String allowedSymbols = "@_-!.#";

// Permitir letras, números y algunos símbolos comunes
if (!Character.isLetterOrDigit(c) && allowedSymbols.indexOf(c) == -1) {
    evt.consume();
}

    }//GEN-LAST:event_txtContraNEmpleadoKeyTyped

    private void txtTelefonoNEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoNEmpleadoKeyTyped
                String text= txtTelefonoNEmpleado.getText();
        int lim=9;
        if(text.length() >=9) evt.consume();
        char c=evt.getKeyChar(); //caracter actual
        if(!(Character.isDigit(c))){evt.consume();}
    }//GEN-LAST:event_txtTelefonoNEmpleadoKeyTyped

    private void txtCorreoNCEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoNCEmpleadoKeyTyped
        String text = txtCorreoNCEmpleado.getText(); // texto actual
int lim = 40;
if (text.length() >= lim) evt.consume();

char c = evt.getKeyChar(); // carácter actual

// Permitidos: letras, números y símbolos básicos de correo
String permitidos = "@._-";
if (!Character.isLetterOrDigit(c) && permitidos.indexOf(c) == -1) {
    evt.consume();
}
    }//GEN-LAST:event_txtCorreoNCEmpleadoKeyTyped

    private void cbxDireccionNEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbxDireccionNEmpleadoKeyTyped
        String text = cbxDireccionNEmpleado.getText(); // texto actual
int lim = 50;
char c = evt.getKeyChar(); // carácter actual

// Limitar longitud
if (text.length() >= lim) {
    evt.consume();
    return;
}

// Permitir letras, números y un solo espacio entre palabras
if (!Character.isLetterOrDigit(c) && c != ' ') {
    evt.consume();
    return;
}

// Evitar espacio inicial
if (text.isEmpty() && c == ' ') {
    evt.consume();
    return;
}

// Evitar más de un espacio seguido
if (c == ' ' && text.endsWith(" ")) {
    evt.consume();
}
    }//GEN-LAST:event_cbxDireccionNEmpleadoKeyTyped

    private void txtNumDocNEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumDocNEmpleadoKeyTyped
        String text = txtNumDocNEmpleado.getText();
int lim = 12; // Ajusta el límite según el tipo de documento

char c = evt.getKeyChar();
if (text.length() >= lim || !Character.isDigit(c)) {
    evt.consume();
}
    }//GEN-LAST:event_txtNumDocNEmpleadoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cbxDireccionNEmpleado;
    private javax.swing.JComboBox<String> cbxNacionaNEmpleado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEmpleados;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField txtApellidosNEmpleados;
    private javax.swing.JTextField txtContraNEmpleado;
    private javax.swing.JTextField txtCorreoNCEmpleado;
    private javax.swing.JTextField txtNUsuarioEmpleado;
    private javax.swing.JTextField txtNombresEmpleado;
    private javax.swing.JTextField txtNumDocNEmpleado;
    private javax.swing.JTextField txtTelefonoNEmpleado;
    // End of variables declaration//GEN-END:variables
}
