/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import java.awt.Dimension;

/**
 *
 * @author LENOVO
 */
public class JInternalFrameRegNuevoUsuario extends javax.swing.JInternalFrame {

    int obtenerIdUsuario=0;
    public JInternalFrameRegNuevoUsuario() {
        initComponents();
        this.setSize(new Dimension(420,469));
        this.setTitle("Registrar Nuevo Usuario");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtNumDocNUsuario = new javax.swing.JTextField();
        txtApellidosNUsuario = new javax.swing.JTextField();
        txtNUsuario = new javax.swing.JTextField();
        txtContraNUsuario = new javax.swing.JTextField();
        txtTelefonoNUsuario = new javax.swing.JTextField();
        txtCorreoNUsuario = new javax.swing.JTextField();
        cbxTipDocNUsuario = new javax.swing.JComboBox<>();
        cbxDireccionNUsuario = new javax.swing.JTextField();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        cbxDistritoNUsuario = new javax.swing.JComboBox<>();
        txtNombresNUsuario = new javax.swing.JTextField();
        cbxNacionaNUsuario = new javax.swing.JComboBox<>();

        jTextField3.setText("jTextField3");

        jTextField5.setText("jTextField5");

        jRadioButton1.setText("jRadioButton1");

        jButton1.setText("jButton1");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Nuevo Usuario");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 0, 170, 32);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nombres:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 50, 59, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Apellidos:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 80, 58, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Usuario");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 110, 47, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Contraseña");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 140, 70, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Telefono");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 170, 52, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Correo");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 200, 42, 20);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Nacionalidad");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 230, 78, 20);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Distrito");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 260, 45, 20);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Direccion");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 290, 56, 20);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Sexo:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(20, 320, 31, 20);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Tipo de Documento:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(20, 350, 124, 20);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Numero de Documento:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(20, 380, 148, 20);

        txtNumDocNUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumDocNUsuarioKeyTyped(evt);
            }
        });
        jPanel1.add(txtNumDocNUsuario);
        txtNumDocNUsuario.setBounds(200, 380, 180, 22);

        txtApellidosNUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidosNUsuarioKeyTyped(evt);
            }
        });
        jPanel1.add(txtApellidosNUsuario);
        txtApellidosNUsuario.setBounds(200, 80, 180, 22);

        txtNUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNUsuarioKeyTyped(evt);
            }
        });
        jPanel1.add(txtNUsuario);
        txtNUsuario.setBounds(200, 110, 180, 22);

        txtContraNUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraNUsuarioActionPerformed(evt);
            }
        });
        txtContraNUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContraNUsuarioKeyTyped(evt);
            }
        });
        jPanel1.add(txtContraNUsuario);
        txtContraNUsuario.setBounds(200, 140, 180, 22);

        txtTelefonoNUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoNUsuarioActionPerformed(evt);
            }
        });
        txtTelefonoNUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoNUsuarioKeyTyped(evt);
            }
        });
        jPanel1.add(txtTelefonoNUsuario);
        txtTelefonoNUsuario.setBounds(200, 170, 180, 22);

        txtCorreoNUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCorreoNUsuarioKeyTyped(evt);
            }
        });
        jPanel1.add(txtCorreoNUsuario);
        txtCorreoNUsuario.setBounds(200, 200, 180, 22);

        cbxTipDocNUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI", "carne de extranjeria", "pasaporte" }));
        jPanel1.add(cbxTipDocNUsuario);
        cbxTipDocNUsuario.setBounds(200, 350, 180, 22);

        cbxDireccionNUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cbxDireccionNUsuarioKeyTyped(evt);
            }
        });
        jPanel1.add(cbxDireccionNUsuario);
        cbxDireccionNUsuario.setBounds(200, 290, 180, 22);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Mujer");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(220, 320, 60, 21);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Hombre");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton3);
        jRadioButton3.setBounds(300, 320, 70, 21);

        cbxDistritoNUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Especificado", "Peruana", "Extranjera" }));
        cbxDistritoNUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDistritoNUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(cbxDistritoNUsuario);
        cbxDistritoNUsuario.setBounds(200, 260, 180, 22);

        txtNombresNUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresNUsuarioActionPerformed(evt);
            }
        });
        txtNombresNUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombresNUsuarioKeyTyped(evt);
            }
        });
        jPanel1.add(txtNombresNUsuario);
        txtNombresNUsuario.setBounds(200, 50, 180, 22);

        cbxNacionaNUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Especificado", "Peruana", "Extranjera" }));
        jPanel1.add(cbxNacionaNUsuario);
        cbxNacionaNUsuario.setBounds(200, 230, 180, 22);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void txtNUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNUsuarioKeyTyped
      String text = txtNUsuario.getText(); // texto actual
int lim = 30;
if (text.length() >= lim) evt.consume();

char c = evt.getKeyChar(); // carácter actual

// Permite solo letras y máximo un espacio
if (!Character.isLetter(c) && c != ' ') {
    evt.consume();
    return;
}

// Solo se permite un espacio en todo el texto
if (c == ' ' && text.contains(" ")) {
    evt.consume();
}

    }//GEN-LAST:event_txtNUsuarioKeyTyped

    private void cbxDistritoNUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDistritoNUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDistritoNUsuarioActionPerformed

    private void txtNombresNUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresNUsuarioKeyTyped
        String text= txtNombresNUsuario.getText();//texto actual
        int lim=30;
        if(text.length()>= lim) evt.consume();
        
        char c= evt.getKeyChar();//c= caracter actual
        // Permite solo letras
        if (!Character.isLetter(c) && c != ' ') {
        evt.consume();
        return;
        }
        // Permite máximo un espacio
        if (c == ' ' && text.contains(" ")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombresNUsuarioKeyTyped

    private void txtNombresNUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresNUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresNUsuarioActionPerformed

    private void txtApellidosNUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosNUsuarioKeyTyped
        String text= txtApellidosNUsuario.getText();//texto actual
        int lim=30;
        if(text.length()>= lim) evt.consume();
        
        char c= evt.getKeyChar();//c= caracter actual
        // Permite solo letras
        if (!Character.isLetter(c) && c != ' ') {
        evt.consume();
        return;
        }
        // Permite máximo un espacio
        if (c == ' ' && text.contains(" ")) {
            evt.consume();
        }
        
    }//GEN-LAST:event_txtApellidosNUsuarioKeyTyped

    private void txtContraNUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraNUsuarioKeyTyped
        String text = txtContraNUsuario.getText();
int lim = 24;
if (text.length() >= lim) {
    evt.consume();
}

char c = evt.getKeyChar();
String allowedSymbols = "@_-!.#";

// Permitir letras, números y algunos símbolos comunes
if (!Character.isLetterOrDigit(c) && allowedSymbols.indexOf(c) == -1) {
    evt.consume();
}

    }//GEN-LAST:event_txtContraNUsuarioKeyTyped

    private void txtTelefonoNUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoNUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoNUsuarioActionPerformed

    private void txtTelefonoNUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoNUsuarioKeyTyped
        String text= txtTelefonoNUsuario.getText();
        int lim=9;
        if(text.length() >=9) evt.consume();
        char c=evt.getKeyChar(); //caracter actual
        if(!(Character.isDigit(c))){evt.consume();}
    }//GEN-LAST:event_txtTelefonoNUsuarioKeyTyped

    private void txtContraNUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraNUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraNUsuarioActionPerformed

    private void txtCorreoNUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoNUsuarioKeyTyped
String text = txtCorreoNUsuario.getText(); // texto actual
int lim = 40;
if (text.length() >= lim) evt.consume();

char c = evt.getKeyChar(); // carácter actual

// Permitidos: letras, números y símbolos básicos de correo
String permitidos = "@._-";
if (!Character.isLetterOrDigit(c) && permitidos.indexOf(c) == -1) {
    evt.consume();
}
    }//GEN-LAST:event_txtCorreoNUsuarioKeyTyped

    private void txtNumDocNUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumDocNUsuarioKeyTyped
String text = txtNumDocNUsuario.getText();
int lim = 12; // Ajusta el límite según el tipo de documento

char c = evt.getKeyChar();
if (text.length() >= lim || !Character.isDigit(c)) {
    evt.consume();
}
    }//GEN-LAST:event_txtNumDocNUsuarioKeyTyped

    private void cbxDireccionNUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbxDireccionNUsuarioKeyTyped
String text = cbxDireccionNUsuario.getText(); // texto actual
int lim = 50;
char c = evt.getKeyChar(); // carácter actual

// Limitar longitud
if (text.length() >= lim) {
    evt.consume();
    return;
}

// Permitir letras, números y un solo espacio entre palabras
if (!Character.isLetterOrDigit(c) && c != ' ') {
    evt.consume();
    return;
}

// Evitar espacio inicial
if (text.isEmpty() && c == ' ') {
    evt.consume();
    return;
}

// Evitar más de un espacio seguido
if (c == ' ' && text.endsWith(" ")) {
    evt.consume();
}
    }//GEN-LAST:event_cbxDireccionNUsuarioKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JTextField cbxDireccionNUsuario;
    private javax.swing.JComboBox<String> cbxDistritoNUsuario;
    private javax.swing.JComboBox<String> cbxNacionaNUsuario;
    private javax.swing.JComboBox<String> cbxTipDocNUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField txtApellidosNUsuario;
    private javax.swing.JTextField txtContraNUsuario;
    private javax.swing.JTextField txtCorreoNUsuario;
    private javax.swing.JTextField txtNUsuario;
    private javax.swing.JTextField txtNombresNUsuario;
    private javax.swing.JTextField txtNumDocNUsuario;
    private javax.swing.JTextField txtTelefonoNUsuario;
    // End of variables declaration//GEN-END:variables
}
